services:
  postgres:
    image: postgres:14.5
    ports:
      - '5466:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db_data:
